### ISSUE TITLE
Validator

### ISSUE THREAD

**Issue by phuicy** [crdelozier/ironclad#2]
Is there any plans to add the validator to this project. I would find it very helpful.
If its in an unfinished state I can help to bring it to a finished state.

Thanks,
Guy

**Comment by crdelozier** [comment]
I haven't worked on this project for a while, so I can't recall exactly what state the validator was in.  I'm fairly sure that I didn't add it because it wasn't working with the most recent version of clang (as of 1 year ago), and I was hoping to fix that before adding it to the repository.  Due to other project constraints, I haven't been able to reach that goal.  I've added what I think is the most recent version of the static validator.  It should check all of the major Ironclad C++ rules.  However, it almost definitely will not work with the current version of clang.

**Comment by phuicy** [comment]
Cool, I will have a look.
